import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { userDataInterface } from '@/types/types'
import { useUserStore } from '@/util/loginState'


const inter = Inter({ subsets: ['latin'] })



export const metadata: Metadata = {
  title: '레이드계산기',
  description: 'Generated by create next app',
}



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  
  const checkLogin = async () => {
    try {
        // const localId = JSON.parse(localStorage.hi)
  
        console.log(window.localStorage)
        // const res = await fetch('api/checkAndLogin',{
        //   method:'POST',
        //   body : JSON.stringify({
        //     'id' : id
        //   })
        // })
        // const resData = await res.json()
        // const params: userDataInterface = {
        //   id: resData.id,
        //   api: resData.api,
        //   avatar: resData.avatar,
        //   charList: resData.charList,
        //   global_name: resData.global_name,
        //   username: resData.username
  
        // }
        // if(!setData)
        //   throw new Error('setData가 정의되지 않았다.')
  
        // setData(params);
  
        // if(!id){
          
        // }
          
        
  
      }catch(error) {
  
      }
      
    }
    checkLogin();


  return (
    <html lang="en">
      <body className={inter.className }>{children}</body>
    </html>
  )
}
